
// This file was auto-generated by ML.NET Model Builder. 

using Nalejvarna_MLdotnetIntro_ModelBuilder_Binary_ConsoleApp;

// Create single instance of sample data from first line of dataset for model input
Model.ModelInput sampleData = new Model.ModelInput()
{
    Col0 = @"Pri ""odkryti kariet"" som onemel a az do zaverecnych titulkov ostal v neopisateľnej zimomriavkovej extaze. Nevedel som ci mam plakat, vyskocit od radosti alebo iba potichu sediet a vychutnat si, co mi bolo prave sprostredkovane. Po navrate z kina som zhasol, pustil soundtrack Thomasa Newmana, lahol si a snazil sa udrzat si tu extazu co najdlhsie. The Shawshank Redemption je film, ktory vam v pomalom tempe, za murmi väzenia, vo svete s vlastnymi pravidlami, predstavi dve hlavne a zopar vedľajsich postav, a nasledne vam vysvetli, co im ich stretnutie na tomto mieste bolesti a beznadeje prinieslo. Film o ""nadeji, ktora nam dava kridla"", film s najprekvapivejsim, najsilnejsim a najkrajsim zaverom ever.",
};



Console.WriteLine("Using model to make single prediction -- Comparing actual Col1 with predicted Col1 from sample data...\n\n");


Console.WriteLine($"Col0: {@"Pri ""odkryti kariet"" som onemel a az do zaverecnych titulkov ostal v neopisateľnej zimomriavkovej extaze. Nevedel som ci mam plakat, vyskocit od radosti alebo iba potichu sediet a vychutnat si, co mi bolo prave sprostredkovane. Po navrate z kina som zhasol, pustil soundtrack Thomasa Newmana, lahol si a snazil sa udrzat si tu extazu co najdlhsie. The Shawshank Redemption je film, ktory vam v pomalom tempe, za murmi väzenia, vo svete s vlastnymi pravidlami, predstavi dve hlavne a zopar vedľajsich postav, a nasledne vam vysvetli, co im ich stretnutie na tomto mieste bolesti a beznadeje prinieslo. Film o ""nadeji, ktora nam dava kridla"", film s najprekvapivejsim, najsilnejsim a najkrajsim zaverom ever."}");
Console.WriteLine($"Col1: {1F}");


var sortedScoresWithLabel = Model.PredictAllLabels(sampleData);
Console.WriteLine($"{"Class",-40}{"Score",-20}");
Console.WriteLine($"{"-----",-40}{"-----",-20}");

foreach (var score in sortedScoresWithLabel)
{
    Console.WriteLine($"{score.Key,-40}{score.Value,-20}");
}

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

